version: '3.7'

services:
  czconnect-backend:
    container_name: czconnect-backend
    image: czfluttercontainers.azurecr.io/czconnect-backend:latest
    build:
      context: backend
      dockerfile: Dockerfile-backend
    env_file:
      - backend/.env
    ports:
      - 3000:3000
    networks:
      - czconnect
  

  mssql-db:
    build:
      context: backend
      dockerfile: Dockerfile-mssql
    container_name: mssql-db
    image: czfluttercontainers.azurecr.io/mssql-db:latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=3Q%8C7`5e_dXZ#H
    volumes:
      - mssql:/var/opt/mssql/data
    networks:
      - czconnect
 


  flutter-web:
    image: czfluttercontainers.azurecr.io/czconnect-flutter-web:latest
    build:
      context: ./cz_app
      target: builder
    ports:
      - 3011:3011
    command: [ "flutter", "run", "-d", "web-server", "--web-port", "3011", "--web-hostname", "0.0.0.0" ]
networks:
  czconnect:

volumes:
  mssql:
  prometheus_data:
  grafana_data: