version: '3.9'

services:
  czconnect-backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - czconnect
    labels:
      - "okteto.deployment.ignore=true"

  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD="3Q%8C7`5e_dXZ#H
    volumes:
      - mssql:/var/opt/mssql/data
    networks:
      - czconnect
    labels:
      - "okteto.deployment.ignore=true"

  flutter-web:
    build:
      context: ./cz_app
      target: builder
    ports:
      - 3011:3011
    command: [ "flutter", "run", "-d", "web-server", "--web-port", "3011", "--web-hostname", "0.0.0.0" ]
#    labels:
#      - "okteto.autocreate=true"
#      - "okteto.push=true"
#      - "okteto.name=flutter-web"
#      - "okteto.disk-size=4.8G"
#      - "okteto.build.target=builder"
#      - "okteto.build.context=./cz_app"
#      - "okteto.build.args=--no-pub"

networks:
  czconnect:

volumes:
  mssql:

