version: '3.9'

services:  
  czconnect-backend:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - czconnect
  
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      # Password is sha256 of the string 'czconnect'
      - MSSQL_SA_PASSWORD=3123db6a563c87fcf30ae8c6fa1d88a684635b268b261264de6f6c64b6845516
    volumes:
      - mssql:/var/opt/mssql/data
    networks:
      - czconnect

networks:
  czconnect:

volumes:
  mssql:

  