FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /usr/src/app

# Copy everything
COPY . .
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
# Use root user
USER root
WORKDIR /usr/src/app
COPY --from=build-env /usr/src/app/out .

ENTRYPOINT [ "dotnet", "backend.dll" ]
