version: '3.9'

services:  
  czconnect-backend:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - czconnect
  
  product-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=keig0edw8woordjonguh
    volumes:
      - mssql:/var/opt/mssql/data
    networks:
      - czconnect

networks:
  czconnect:

volumes:
  mssql:

  