version: '3'

services:

  apigateway:
    build: ./apigateway
    command: ./node_modules/.bin/nodemon ./src/apigateway_main.js
    env_file:
      - ./apigateway/.env
    volumes:
      - ./apigateway/src:/usr/src/app/src
    ports:
      - 3000:3000
    networks:
      - servicebus
    depends_on:
      - rabbitmq
    
  applicant-forms-service:
    build: ./applicant-forms
    command: ./node_modules/.bin/nodemon ./src/applicant_form_main.js
    env_file:
      - ./applicant-forms/.env
    volumes:
      - ./applicant-forms/src:/usr/src/app/src
    networks:
      - servicebus
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    networks:
      - servicebus

networks:
  servicebus: