version: '4'

services:
  czconnect-backend:
    container_name: czconnect-backend
    image: czfluttercontainers.azurecr.io/czconnect-backend:latest
    build:
      context: .
      dockerfile: Dockerfile-backend
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - czconnect

  mssql-db:
    build:
      context: .
      dockerfile: Dockerfile-mssql
    image: czfluttercontainers.azurecr.io/mssql-db:latest
    user: root
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=3Q%8C7`5e_dXZ#H
    volumes:
      - mssql:/var/opt/mssql/data
    networks:
      - czconnect

networks:
  czconnect:

volumes:
  mssql: {}