version: '3.9'

services:  
  czconnect-backend:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - czconnect
  
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD="3Q%8C7`5e_dXZ#H
    volumes:
      - mssql:/var/opt/mssql/data
    networks:
      - czconnect

networks:
  czconnect:

volumes:
  mssql:

  
