global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']
        
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'proxy'
    scrape_interval: 5s
    static_configs:
      - targets: ['proxy:5000']

  - job_name: 'mysql'
    scrape_interval: 5s
    static_configs:
      - targets: ['mssql-db:1433']

  - job_name: 'gateway'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'czconnect-backend:3000' ]

  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana:5000']
