// <auto-generated />
using System;
using CZConnect.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CZConnect.Models.ApplicantForm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicantForms");
                });

            modelBuilder.Entity("CZConnect.Models.Referral", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("employeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("participantEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("participantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("registrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Referrals");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            employeeName = "CZ-Medewerker",
                            participantEmail = "cmberge@avans.nl",
                            participantName = "Coen",
                            registrationDate = new DateTime(2023, 3, 23, 13, 18, 26, 310, DateTimeKind.Local).AddTicks(7564),
                            status = "Afgerond"
                        },
                        new
                        {
                            id = 2L,
                            employeeName = "CZ-Medewerker",
                            participantEmail = "m1@avans.nl",
                            participantName = "Marijn 1",
                            registrationDate = new DateTime(2023, 3, 23, 13, 18, 26, 310, DateTimeKind.Local).AddTicks(7634),
                            status = "In afwachting"
                        },
                        new
                        {
                            id = 3L,
                            employeeName = "CZ-Medewerker",
                            participantEmail = "m2@avans.nl",
                            participantName = "Marijn 2",
                            registrationDate = new DateTime(2023, 3, 23, 13, 18, 26, 310, DateTimeKind.Local).AddTicks(7638),
                            status = "Afgerond"
                        },
                        new
                        {
                            id = 4L,
                            employeeName = "CZ-Medewerker",
                            participantEmail = "jos@avans.nl",
                            participantName = "Jos",
                            registrationDate = new DateTime(2023, 3, 23, 13, 18, 26, 310, DateTimeKind.Local).AddTicks(7643),
                            status = "Afgerond"
                        },
                        new
                        {
                            id = 5L,
                            employeeName = "CZ-Medewerker",
                            participantEmail = "jedrek@avans.nl",
                            participantName = "Jedrek",
                            registrationDate = new DateTime(2023, 3, 23, 13, 18, 26, 310, DateTimeKind.Local).AddTicks(7647),
                            status = "Afgerond"
                        },
                        new
                        {
                            id = 6L,
                            employeeName = "CZ-Medewerker",
                            participantEmail = "wballeko@avans.nl",
                            participantName = "William",
                            registrationDate = new DateTime(2023, 3, 23, 13, 18, 26, 310, DateTimeKind.Local).AddTicks(7652),
                            status = "In afwachting"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
