name: Flutter Web Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.4'  # Set the version of Flutter to install

      # Install dependencies
      - name: Get dependencies
        run: flutter pub get
        working-directory: cz_app

      # Run tests
      - name: Run tests
        run: flutter test test/web_test.dart
        working-directory: cz_app
