name: Flutter Web Test and Build

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  flutter_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.6'  # Set the version of Flutter to install

      # Install dependencies
      - name: Get dependencies
        run: flutter pub get
        working-directory: cz_app

      # Analyse project
      - name: Run analyze
        run: flutter analyze --pub --no-fatal-infos --no-fatal-warnings
        working-directory: cz_app

      # Run tests
      - name: Run tests
        run: flutter test
        working-directory: cz_app

      # Clean project
      - name: clean flutter
        run: flutter clean
        working-directory: cz_app

      # Build Web
      - name: build flutter (Web)
        run: flutter build web
        working-directory: cz_app

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: cz_app/build/web/

  Build_web:
    name: Build flutter (Web)
    needs: flutter_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: web-app

      # Your steps to push the build app to azure goes here
