name: 'nightly artifacts cleanup'
on:
  push:
   

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.TOKEN }}
          expire-in: 0days # Setting this to 0 will delete all artifacts
